package Vistas;

import java.time.LocalDate;
import java.time.ZoneId;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

public class ProgramarCita extends javax.swing.JInternalFrame {

    private List<String> ciudadanosRegistrados;
    private List<String> centrosRegistrados;
    private List<String> vacunasRegistradas;

    public ProgramarCita(List<String> ciudadanos, List<String> centros, List<String> vacunas) {
    
        initComponents();
        ciudadanosRegistrados = ciudadanos;
        centrosRegistrados = centros;
        vacunasRegistradas = vacunas;

        // Llena los ComboBox con los datos
        cbCiudadanosRegistrados.setModel(new DefaultComboBoxModel<>(ciudadanos.toArray(new String[0])));
        cbCentrosRegistrados.setModel(new DefaultComboBoxModel<>(centros.toArray(new String[0])));
        cbVacunasRegistradas.setModel(new DefaultComboBoxModel<>(vacunas.toArray(new String[0])));
    }



/**
 * This method is called from within the constructor to initialize the form.
 * WARNING: Do NOT modify this code. The content of this method is always
 * regenerated by the Form Editor.
 */
@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cbCiudadanosRegistrados = new javax.swing.JComboBox<>();
        cbVacunasRegistradas = new javax.swing.JComboBox<>();
        cbCentrosRegistrados = new javax.swing.JComboBox<>();
        jDCalendario = new com.toedter.calendar.JDateChooser();
        rb3dosis = new javax.swing.JRadioButton();
        rb2dosis = new javax.swing.JRadioButton();
        rb1dosis = new javax.swing.JRadioButton();
        jLPacienteRegistrado = new javax.swing.JLabel();
        jLCalendario = new javax.swing.JLabel();
        jLVacunasRegistradas = new javax.swing.JLabel();
        jLCentroRegistrado = new javax.swing.JLabel();
        jLNroDosis = new javax.swing.JLabel();
        rb4dosis = new javax.swing.JRadioButton();
        jBAplicarVacuna = new javax.swing.JButton();

        cbCiudadanosRegistrados.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbCiudadanosRegistrados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCiudadanosRegistradosActionPerformed(evt);
            }
        });

        cbVacunasRegistradas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbCentrosRegistrados.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        rb3dosis.setText("3ra dosis");
        rb3dosis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb3dosisActionPerformed(evt);
            }
        });

        rb2dosis.setText("2da dosis");

        rb1dosis.setText("1era dosis");

        jLPacienteRegistrado.setText("Elegir paciente registrado:");

        jLCalendario.setText("Elegir fecha de turno:");

        jLVacunasRegistradas.setText("Elegir vacuna disponible:");

        jLCentroRegistrado.setText("Asignar Centro disponible:");

        jLNroDosis.setText("Elegir dosis:");

        rb4dosis.setText("4ta dosis");
        rb4dosis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb4dosisActionPerformed(evt);
            }
        });

        jBAplicarVacuna.setText("Aplicar nueva dosis");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLCentroRegistrado)
                            .addComponent(jLPacienteRegistrado)
                            .addComponent(jLVacunasRegistradas))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbVacunasRegistradas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbCiudadanosRegistrados, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbCentrosRegistrados, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jBAplicarVacuna)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLCalendario)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jDCalendario, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLNroDosis)
                                .addGap(18, 18, 18)
                                .addComponent(rb1dosis)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rb2dosis)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rb3dosis)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rb4dosis)))))
                .addGap(25, 25, 25))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbCiudadanosRegistrados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLPacienteRegistrado))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLCentroRegistrado)
                    .addComponent(cbCentrosRegistrados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbVacunasRegistradas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLVacunasRegistradas))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLNroDosis)
                    .addComponent(rb1dosis)
                    .addComponent(rb2dosis)
                    .addComponent(rb3dosis)
                    .addComponent(rb4dosis))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDCalendario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLCalendario))
                .addGap(38, 38, 38)
                .addComponent(jBAplicarVacuna)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void cbCiudadanosRegistradosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCiudadanosRegistradosActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cbCiudadanosRegistradosActionPerformed

    private void rb3dosisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb3dosisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb3dosisActionPerformed

    private void rb4dosisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb4dosisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb4dosisActionPerformed

    private void jBAplicarVacunaActionPerformed(java.awt.event.ActionEvent evt) {
        String pacienteSeleccionado = cbCiudadanosRegistrados.getSelectedItem().toString();
        String centroSeleccionado = cbCentrosRegistrados.getSelectedItem().toString();
        String vacunaSeleccionada = cbVacunasRegistradas.getSelectedItem().toString();
        LocalDate fechaSeleccionada = LocalDate.ofInstant(jDCalendario.getDate().toInstant(), ZoneId.systemDefault());
        
        JOptionPane.showMessageDialog(this, "Cita programada con éxito", "Éxito", JOptionPane.INFORMATION_MESSAGE);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbCentrosRegistrados;
    private javax.swing.JComboBox<String> cbCiudadanosRegistrados;
    private javax.swing.JComboBox<String> cbVacunasRegistradas;
    private javax.swing.JButton jBAplicarVacuna;
    private com.toedter.calendar.JDateChooser jDCalendario;
    private javax.swing.JLabel jLCalendario;
    private javax.swing.JLabel jLCentroRegistrado;
    private javax.swing.JLabel jLNroDosis;
    private javax.swing.JLabel jLPacienteRegistrado;
    private javax.swing.JLabel jLVacunasRegistradas;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton rb1dosis;
    private javax.swing.JRadioButton rb2dosis;
    private javax.swing.JRadioButton rb3dosis;
    private javax.swing.JRadioButton rb4dosis;
    // End of variables declaration//GEN-END:variables
}